**Registro de Ocupação Hospitalar COVID-19**

Utilizei os Dados Abertos do Governo Federal referente a ocupação hospitalar resultante da COVID-19 no ano de 2022.

Podemos fazer o download dos dados em https://dados.gov.br/dados/conjuntos-dados/registro-de-ocupacao-hospitalar-covid-19

O módulo Internações foi desenvolvido para registro da ocupação de leitos clínicos e de Unidade de Terapia Intensiva (UTI) SUS destinados para atendimento aos pacientes com casos suspeitos ou confirmados da COVID-19 (ocupação SRAG / COVID-19).

Alguns estados apresentam sistemas próprios de registro de ocupação e para esses foi disponibilizado uma API que transfere os dados dos estados para o sistema ESUS NOTIFICA - Módulo Internações SUS, em vigor a partir de abril de 2020.

In [1]:
import pandas as pd

In [14]:
# carregando o arquivo e especificando a coluna com datas
df = pd.read_csv("esus-vepi.LeitoOcupacao_2022.csv", sep=",", 
                 parse_dates=["dataNotificacao"])
df

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,...,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,validado,_created_at,_updated_at
0,641508,PBGTlqtFBP,2022-01-17 03:00:00+00:00,2379341,13.0,8.0,0.0,0.0,0.0,1.0,...,parse-cloud,_User$m6WdvZgbBS,Santa Catarina,Mafra,Santa Catarina,Mafra,False,False,2021-02-15T11:08:07.797Z,2022-01-17T21:56:42.351Z
1,1275198,ipPHkH1yIB,2022-01-05 03:00:00+00:00,2594366,NaN,NaN,NaN,NaN,0.0,0.0,...,parse-cloud,_User$C2nTBR5lmy,Paraná,Umuarama,Paraná,Umuarama,False,False,2021-12-08T10:42:04.123Z,2022-01-05T14:17:35.799Z
2,1290474,oDyVTndNXc,2022-01-01 03:00:50.682000+00:00,2747871,NaN,NaN,NaN,NaN,1.0,9.0,...,parse-cloud,_User$APEoiAf61c,São Paulo,Ilhabela,São Paulo,Ilhabela,False,False,2022-01-01T03:34:58.234Z,2022-01-01T03:34:58.234Z
3,1290489,cTrwNtInVV,2022-01-01 03:00:08.570000+00:00,2082497,NaN,NaN,NaN,NaN,0.0,1.0,...,parse-cloud,_User$q0FgtTNz2d,São Paulo,Bernardino de Campos,São Paulo,Bernardino de Campos,False,False,2022-01-01T04:50:29.194Z,2022-01-01T04:50:29.194Z
4,1290490,CPkiO32WyI,2022-01-01 03:00:14.691000+00:00,2092980,NaN,NaN,NaN,NaN,0.0,0.0,...,parse-cloud,_User$u4yOaQOJlf,São Paulo,Bastos,São Paulo,Bastos,False,False,2022-01-01T05:01:31.468Z,2022-01-01T05:01:31.468Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291574,1605618,HAoMAbGpNY,2022-02-23 03:00:00+00:00,2147823,NaN,NaN,NaN,NaN,0.0,0.0,...,parse-cloud,_User$IEHhSDzwrs,Minas Gerais,São Roque de Minas,Minas Gerais,São Roque de Minas,False,False,2023-02-23T13:21:25.285Z,2023-02-23T13:21:25.285Z
291575,1605619,XIuDWUocoJ,2022-02-23 03:00:00+00:00,2147823,NaN,NaN,NaN,NaN,0.0,0.0,...,parse-cloud,_User$IEHhSDzwrs,Minas Gerais,São Roque de Minas,Minas Gerais,São Roque de Minas,False,False,2023-02-23T13:21:53.073Z,2023-02-23T13:21:53.073Z
291576,1605622,kwReOPPIFf,2022-03-22 03:00:00+00:00,0010502,NaN,NaN,NaN,NaN,0.0,17.0,...,parse-cloud,_User$n71qFbuRHI,Distrito Federal,Brasília,Distrito Federal,Brasília,False,False,2023-02-23T13:23:47.602Z,2023-02-23T13:23:47.602Z
291577,1605626,5CACzrDGZD,2022-02-23 03:00:00+00:00,2082934,NaN,NaN,NaN,NaN,0.0,0.0,...,parse-cloud,_User$Kw5oEHlD9E,São Paulo,Taguaí,São Paulo,Taguaí,False,False,2023-02-23T13:32:02.053Z,2023-02-23T13:32:02.053Z
291578,1605866,GWb6jkWnEd,2022-02-24 03:00:00+00:00,2084317,NaN,NaN,NaN,NaN,0.0,0.0,...,parse-cloud,_User$mrXGR7Ze6b,São Paulo,Amparo,São Paulo,Amparo,False,False,2023-02-24T10:27:06.878Z,2023-02-24T10:27:06.878Z

In [15]:
# visualizando os tipos de dados
df.dtypes

Unnamed: 0                             int64
_id                                   object
dataNotificacao          datetime64[ns, UTC]
cnes                                  object
ocupacaoSuspeitoCli                  float64
ocupacaoSuspeitoUti                  float64
ocupacaoConfirmadoCli                float64
ocupacaoConfirmadoUti                float64
ocupacaoCovidUti                     float64
ocupacaoCovidCli                     float64
ocupacaoHospitalarUti                float64
ocupacaoHospitalarCli                float64
saidaSuspeitaObitos                  float64
saidaSuspeitaAltas                   float64
saidaConfirmadaObitos                float64
saidaConfirmadaAltas                 float64
origem                                object
_p_usuario                            object
estadoNotificacao                     object
municipioNotificacao                  object
estado                                object
municipio                             object
excluido                                bool
validado                                bool
_created_at                           object
_updated_at                           object
dtype: object

In [16]:
# acessando a coluna "dataNotificacao"
df.dataNotificacao

0               2022-01-17 03:00:00+00:00
1               2022-01-05 03:00:00+00:00
2        2022-01-01 03:00:50.682000+00:00
3        2022-01-01 03:00:08.570000+00:00
4        2022-01-01 03:00:14.691000+00:00
                       ...
291574          2022-02-23 03:00:00+00:00
291575          2022-02-23 03:00:00+00:00
291576          2022-03-22 03:00:00+00:00
291577          2022-02-23 03:00:00+00:00
291578          2022-02-24 03:00:00+00:00
Name: dataNotificacao, Length: 291579, dtype: datetime64[ns, UTC]

In [17]:
# acessando o mês de cada data
df.dataNotificacao.dt.month

0         1
1         1
2         1
3         1
4         1
         ..
291574    2
291575    2
291576    3
291577    2
291578    2
Name: dataNotificacao, Length: 291579, dtype: int64